// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: service_joke.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JokeServiceClient is the client API for JokeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JokeServiceClient interface {
	CreateJoke(ctx context.Context, in *CreateJokeRequest, opts ...grpc.CallOption) (*CreateJokeResponse, error)
	GetJoke(ctx context.Context, in *GetJokeRequest, opts ...grpc.CallOption) (*GetJokeResponse, error)
}

type jokeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJokeServiceClient(cc grpc.ClientConnInterface) JokeServiceClient {
	return &jokeServiceClient{cc}
}

func (c *jokeServiceClient) CreateJoke(ctx context.Context, in *CreateJokeRequest, opts ...grpc.CallOption) (*CreateJokeResponse, error) {
	out := new(CreateJokeResponse)
	err := c.cc.Invoke(ctx, "/pb.JokeService/CreateJoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jokeServiceClient) GetJoke(ctx context.Context, in *GetJokeRequest, opts ...grpc.CallOption) (*GetJokeResponse, error) {
	out := new(GetJokeResponse)
	err := c.cc.Invoke(ctx, "/pb.JokeService/GetJoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JokeServiceServer is the server API for JokeService service.
// All implementations must embed UnimplementedJokeServiceServer
// for forward compatibility
type JokeServiceServer interface {
	CreateJoke(context.Context, *CreateJokeRequest) (*CreateJokeResponse, error)
	GetJoke(context.Context, *GetJokeRequest) (*GetJokeResponse, error)
	mustEmbedUnimplementedJokeServiceServer()
}

// UnimplementedJokeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJokeServiceServer struct {
}

func (UnimplementedJokeServiceServer) CreateJoke(context.Context, *CreateJokeRequest) (*CreateJokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJoke not implemented")
}
func (UnimplementedJokeServiceServer) GetJoke(context.Context, *GetJokeRequest) (*GetJokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJoke not implemented")
}
func (UnimplementedJokeServiceServer) mustEmbedUnimplementedJokeServiceServer() {}

// UnsafeJokeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JokeServiceServer will
// result in compilation errors.
type UnsafeJokeServiceServer interface {
	mustEmbedUnimplementedJokeServiceServer()
}

func RegisterJokeServiceServer(s grpc.ServiceRegistrar, srv JokeServiceServer) {
	s.RegisterService(&JokeService_ServiceDesc, srv)
}

func _JokeService_CreateJoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).CreateJoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JokeService/CreateJoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).CreateJoke(ctx, req.(*CreateJokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JokeService_GetJoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JokeServiceServer).GetJoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.JokeService/GetJoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JokeServiceServer).GetJoke(ctx, req.(*GetJokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JokeService_ServiceDesc is the grpc.ServiceDesc for JokeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JokeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.JokeService",
	HandlerType: (*JokeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateJoke",
			Handler:    _JokeService_CreateJoke_Handler,
		},
		{
			MethodName: "GetJoke",
			Handler:    _JokeService_GetJoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_joke.proto",
}
